ci: fix alpine image + fix vcpkg cache

diff --git a/.github/workflows/thread-sanitizer.yaml b/.github/workflows/thread-sanitizer.yaml
--- a/.github/workflows/thread-sanitizer.yaml
+++ b/.github/workflows/thread-sanitizer.yaml
@@ -80,14 +80,14 @@ jobs:
       - name: 'Find TSan library path'
         id: tsan-lib
         run: |
-          # TSAN_LIB=$(find /usr/lib -name "libtsan.so.0" 2>/dev/null | head -1)
-          # if [ -z "$TSAN_LIB" ]; then
-          #   echo "Error: libtsan.so.0 not found"
-          #   exit 1
-          # fi
-          # echo "tsan_lib=$TSAN_LIB" >> $GITHUB_OUTPUT
-          # echo "Found TSan library at: $TSAN_LIB"
-          echo "tsan_lib=/usr/lib/x86_64-linux-gnu/libtsan.so.0" >> $GITHUB_OUTPUT
+          TSAN_LIB=$(find /usr/lib -name "libtsan.so.0" 2>/dev/null | head -1)
+          if [ -z "$TSAN_LIB" ]; then
+            echo "Error: libtsan.so.0 not found"
+            exit 1
+          fi
+          echo "tsan_lib=$TSAN_LIB" >> $GITHUB_OUTPUT
+          echo "Found TSan library at: $TSAN_LIB"
+          # echo "tsan_lib=/usr/lib/x86_64-linux-gnu/libtsan.so.0" >> $GITHUB_OUTPUT
 
       # - name: Debugging Tmate
       #   uses: mxschmitt/action-tmate@v3
